regions:
  - global
  - us-east-1
  - us-west-1 
  - us-west-2

blocklist:
  - "999999999999"

# Add this to bypass alias check
accounts-bypass-alias-check:
  - "965087335223"

accounts:
  "965087335223":
    filters:
      EC2DHCPOption:
        - "default"
      EC2InternetGateway:
        - "default" 
      EC2RouteTable:
        - "default"
      EC2Subnet:
        - "default"
      EC2VPC:
        - "default"
      EC2SecurityGroup:
        - "default"
